/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_c_bean_EntryUtils */

#ifndef _Included_com_example_c_bean_EntryUtils
#define _Included_com_example_c_bean_EntryUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_c_bean_EntryUtils
 * Method:    getStringC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_c_bean_EntryUtils_getStringC
  (JNIEnv *, jclass);

/*
 * Class:     com_example_c_bean_EntryUtils
 * Method:    encode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_c_bean_EntryUtils_encode
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_c_bean_EntryUtils
 * Method:    decode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_c_bean_EntryUtils_decode
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
